version: '3'

services:
  backend:
    build:
      context: ./backend-web-desa-sakerta-barat
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/desa_sakerta_barat
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend-web-desa-sakerta-barat
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: desa_sakerta_barat
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
